config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, :events
  end
  get '/admin', to: 'admins#index', as: 'admin_index'


  root 'events#index'

  get 'events_controller/index'
  get 'static_pages/index'
  get 'static_pages/secret'
  
  resources :events do
    resources :attendances, only: [:index, :create]
  end
  resources :charges, only: [:new, :create]
  devise_for :users
  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end




# Envie de t'amuser ? 
#
# Tente avec ce fichier de routes, et tente de te connecter :
#
#
# root 'events#index'
#
# get 'static_pages/secret' 
# resources :events_controller, only: [:index]          #kécécé ?
# resources :static_pages, only: [:index, :secret]
# resources :events
# resources :users, only: [:show]
# devise_for :users

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :administrator, class_name: 'User', dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances

  validates :start_date,  presence: true, if: :not_past?
  validates :duration,    presence: true, if: :mod_5?,
                          numericality: { :greater_than => 0 }
  validates :title,       presence: true,
                          length: { minimum: 5,
                                    maximum: 140 }
  validates :description, presence: true,
                          length: { minimum: 20,
                                    maximum: 1_000 }
  validates :price,       presence: true,
                          numericality: { :greater_than => 0,
                                          :less_than    => 1_000 }
  validates :location,    presence: true

  def not_past?
    self.start_date.future?
  end

  def mod_5?
    self.duration % 5 == 0
  end


end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminsController
  def index
    @events = Event.all.sort
  end

  def show
    @event = Event.find(params[:id])
    @users = User.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all
    puts ">>>>>>>>>>>>>>>>>>>>>>#{@events} <<<<<<<<<<<<<<<<<<<<<<<"
  end
  
  def show
    @event = Event.find(params[:id])
    @attendees = Attendance.where(event_id: @event.id).count
    @administrator = User.where(id: @event.administrator_id)
    puts "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#{@event}"
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(
      start_date:       DateTime.new(params[:start_date_day].split("-")[0].to_i,
                        params[:start_date_day].split("-")[1].to_i,
                        params[:start_date_day].split("-")[2].to_i,
                        params[:start_date_hour].split("-")[0].to_i,
                        params[:start_date_hour].split("-")[1].to_i,
                        params[:start_date_hour].split("-")[2].to_i),
      duration:         params[:duration],
      title:            params[:description],
      description:      params[:description],
      price:            params[:price],
      location:         params[:location],
      administrator_id: params[:administrator_id]
    )

    if @event.save
      redirect_to :root
      flash[:success] = "Event created !"
    else
      render :new
      flash[:danger] = "Couldn't create your event"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/show.html.erb
<div class="container-fluid">
  <div class="row">

    <%= render "admin/side_nav"%>


<br><br><div class="container">

<%= form_with(model: [:admin, @event], url: admin_event_path, method: "patch") do |form| %>
  <div class="form-row">   
    <div class="form-group col-md-6">
      <%= form.label :name, "Title:" %>
      <%= form.text_field :title, id: :title, class: "form-control", placeholder: "#{@event.title}"%>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :name, "Price:" %>
      <%= form.text_field :price, id: :price, class: "form-control", placeholder: "#{@event.price}"%>
    </div>
    
    <div class="form-group col-md-12">
      <%= form.label :name, "Description:" %>
      <%= form.text_field :description, id: :description, class: "form-control", placeholder: "#{@event.description}"%>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :name, "Location:" %>
      <%= form.text_field :location, id: :location, class: "form-control", placeholder: "#{@event.location}"%>
    </div>

    <div class="form-group col-md-2">
      <label for="inputState">Duration</label>
      <select id="inputState" class="form-control">
        <% x = 0 %>
        <% loop do %>
          <option><%= x %></option>
          <% x += 5 %>
          <% break if x >= 50 %>
        <% end %>
      </select>
    </div>

    <div class="form-group col-md-10">
      <%= form.label :name, "Start date:" %>
      <%= form.text_field :start_date, id: :start_date, class: "form-control", placeholder: "#{@event.start_date}"%>
    </div>


  </div>
<% end %>


<form accept-charset="UTF-8" action="/admin/evens/<% @event.id %>" data-remote="true" method="patch">
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Title</label>
      <input class="form-control" id="title" placeholder="<%= @event.title %>">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Price</label>
      <input class="form-control" id="inputPassword4" placeholder="<%= @event.price %>">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Description</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="<%= @event.description %>">
  </div>
  <div class="form-group">
    <label for="inputAddress2">Location</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="<%= @event.location %>">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">Start date</label>
      <input type="text" class="form-control" id="inputCity" placeholder="<%= @event.start_date %>">
    </div>

    <div class="form-group col-md-4">
      <label for="inputZip">Administrator</label>
      <select id="administrator" class="form-control">
        <% @users.each do |user| %>
        <option><%= user.first_name %></option>
        <% end %>
      </select>
    </div>
  </div>
  
  <%= link_to '<button type="submit" class="btn btn-primary">Update</button>'.html_safe, admin_event_path(@event), method: :patch %>
</form>
</div>
  </div>
</div>