config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, :events
  end
  get '/admin', to: 'admins#index', as: 'admin_index'


  root 'events#index'

  get 'events_controller/index'
  get 'static_pages/index'
  get 'static_pages/secret'
  
  resources :events do
    resources :attendances, only: [:index, :create]
  end
  resources :charges, only: [:new, :create]
  devise_for :users
  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end




# Envie de t'amuser ? 
#
# Tente avec ce fichier de routes, et tente de te connecter :
#
#
# root 'events#index'
#
# get 'static_pages/secret' 
# resources :events_controller, only: [:index]          #kécécé ?
# resources :static_pages, only: [:index, :secret]
# resources :events
# resources :users, only: [:show]
# devise_for :users

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :administrator, class_name: 'User', dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances

  validates :start_date,  presence: true, if: :not_past?
  validates :duration,    presence: true, if: :mod_5?,
                          numericality: { :greater_than => 0 }
  validates :title,       presence: true,
                          length: { minimum: 5,
                                    maximum: 140 }
  validates :description, presence: true,
                          length: { minimum: 20,
                                    maximum: 1_000 }
  validates :price,       presence: true,
                          numericality: { :greater_than => 0,
                                          :less_than    => 1_000 }
  validates :location,    presence: true

  def not_past?
    self.start_date.future?
  end

  def mod_5?
    self.duration % 5 == 0
  end


end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminsController
  def index
    @events = Event.all.sort
  end

  def show
    @event = Event.find(params[:id])
    @users = User.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all
    puts ">>>>>>>>>>>>>>>>>>>>>>#{@events} <<<<<<<<<<<<<<<<<<<<<<<"
  end
  
  def show
    @event = Event.find(params[:id])
    @attendees = Attendance.where(event_id: @event.id).count
    @administrator = User.where(id: @event.administrator_id)
    puts "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#{@event}"
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(
      start_date:       DateTime.new(params[:start_date_day].split("-")[0].to_i,
                        params[:start_date_day].split("-")[1].to_i,
                        params[:start_date_day].split("-")[2].to_i,
                        params[:start_date_hour].split("-")[0].to_i,
                        params[:start_date_hour].split("-")[1].to_i,
                        params[:start_date_hour].split("-")[2].to_i),
      duration:         params[:duration],
      title:            params[:description],
      description:      params[:description],
      price:            params[:price],
      location:         params[:location],
      administrator_id: params[:administrator_id]
    )

    if @event.save
      redirect_to :root
      flash[:success] = "Event created !"
    else
      render :new
      flash[:danger] = "Couldn't create your event"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">EventBrite,</h1>
    <p>Les evenements près de chez toi ! (Franglais [ON])</p><br>

    <% if user_signed_in? %>
      <a href="<%= new_event_path %>" class="btn btn-lg btn-outline-info btn-block">New event !</a>
      <br>
    <% end %>

  </div>
</div>


<div class="container">
  <div class="row-fluid marketing" id="gossips">
    <div class="col-xs-1 center-block">
      <div class="card-columns">

        <% @events.each do |event| %>

          <div class="animated wow fadeIn">
            <div class="card" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title"><%= event.title %></h5>
                <h6 class="card-subtitle mb-2 text-muted">Admin: <%= link_to "#{event.administrator.first_name} #{event.administrator.last_name}", user_path(event.administrator.id) %></h6>
                <p class="card-text"><%= event.description[0..50].gsub(/\s\w+\s*$/, ' ...') %></p>
                <%= link_to "plus", event_path(event.id), :class => "btn btn-secondary" %>   
              </div>
            </div>
          </div>
          
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<br><br>
<div class="container">
  <div class="card text-center">
    <div class="card-header">
      <h2>Create a new event</h2>
    </div>
    <div class="card-footer text-muted">

    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="form-signin mt-3">
      
          <%= form_tag events_path, method: :post do %>

            <p><%= label_tag "Date" %>
            <%= text_field_tag "start_date_day", nil, placeholder: "yyyy-mm-dd", class: "form-control"%></p>

            <p><%= label_tag "Hour" %>
            <%= text_field_tag "start_date_hour", nil, placeholder: "hh-mm-ss", class: "form-control"%></p>

            <p><%= label_tag :duration %>
            <%= select_tag "duration", options_for_select(['5', '10', '15'], '15'), class: "form-control" %></p>

            <p><%= label_tag :title %>
            <%= text_field_tag "title", nil, placeholder: "Lorem Ipsum maggle", class: "form-control form-text"%></p>

            <p><%= label_tag :description %>
            <%= text_field_tag "description", nil, placeholder: "Lorem Ipsum Lorem Ipsum ", rows: "4", class: "form-control form-text"%></p>

            <p><%= label_tag :price %>
            <%= text_field_tag "price", nil, placeholder: "42", class: "form-control form-text"%></p>

            <p><%= label_tag :location %>
            <%= text_field_tag "location", nil, placeholder: "Chaux-Les-Crotenay", class: "form-control form-text"%></p>
            
            <%= hidden_field_tag 'administrator_id', current_user.id %>

            <%= submit_tag "Submit", class: "btn btn-large btn-primary" %>
          <% end %>

    </div>

app/views/events/show.html.erb
<br><br>

<div class="container">
  <div class="card text-center">
    <div class="card-header">
      <h2><%= @event.title %></h2>
      <%= link_to 'IMA GOIN', event_attendances_path(event_id: @event.id, ) %>
          
        
      <%= form_tag event_attendances_path(event_id: @event.id) do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
          <label class="amount">
            <span>Amount: $5.00</span>
          </label>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="A month's subscription"
                data-amount="500"
                data-locale="auto"></script>
      <% end %>

    </div>
    <div class="card-body">
      <h5 class="card-title">Beginning: <%= @event.start_date %></h5>
      <p class="card-title">Attendees: <%= @attendees %></p>
    </div>
    <div class="card-footer text-muted"><br>
    </div><br><br>



<div class="card">
  <div class="card-header">
    <h4>Description</h4>
  </div>
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text"><em><%= @event.description %></em></p>
  </div>
</div><br><br>

<div class="card">
  <div class="card-header">
    <h4>About organizer</h4>
  </div>
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text"><em><%= @administrator.first!.first_name + " " + @administrator.first!.last_name %></em></p>
    <p class="card-text">Contact: <%= @administrator.first!.email %></p>
  </div>
</div>

<div class="card">
  <div class="card-header">
    <h4>Reste des infos (la flemme, il est 2H l'ami.e)</h4>
  </div>
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text">Start: <%= @event.start_date %></p>
    <p class="card-text">End: <%= (@event.start_date + (@event.duration * 60)) %></p>
    <p class="card-text">Price: <%= @event.price %> Ğ1</p>
    <p class="card-text">Location: <%= @event.location %></p>


  </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>