config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, :events
  end
  get '/admin', to: 'admins#index', as: 'admin_index'


  root 'events#index'

  get 'events_controller/index'
  get 'static_pages/index'
  get 'static_pages/secret'
  
  resources :events do
    resources :attendances, only: [:index, :create]
  end
  resources :charges, only: [:new, :create]
  devise_for :users
  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end




# Envie de t'amuser ? 
#
# Tente avec ce fichier de routes, et tente de te connecter :
#
#
# root 'events#index'
#
# get 'static_pages/secret' 
# resources :events_controller, only: [:index]          #kécécé ?
# resources :static_pages, only: [:index, :secret]
# resources :events
# resources :users, only: [:show]
# devise_for :users

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :administrations, foreign_key: 'administrator_id', class_name: "Event"
  
  after_create :welcome_send 

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
  def index
    @users = User.all.sort
  end

  def show
    @user = User.find(params[:id])
    @user_events_organizing = []
    @user_events = []
    events_id = []
    # On cherche les EVENT_ID auquel notre @USER participe
    # > On insert l'EVENT_ID dans #find() afin d'effectuer une requette sur la table EVENTS
    @user.attendances.each do |attendance|
      event_id = attendance.event_id
      Event.find(event_id).administrator_id == current_user.id ?
      @user_events_organizing << Event.find(event_id) :
      @user_events << Event.find(event_id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :own_profil?, only: [:show]

  def show
    # skinny controller they said... (j'aurais du utiliser des where j'crois)
    # trop sale pour répondre au cahier des charges ahah
    @user = User.find(params[:id])
    @user_events_organizing = []
    @user_events = []
    events_id = []
    # On cherche les EVENT_ID auquel notre @USER participe
    # > On insert l'EVENT_ID dans #find() afin d'effectuer une requette sur la table EVENTS
    @user.attendances.each do |attendance|
      event_id = attendance.event_id
      Event.find(event_id).administrator_id == current_user.id ?
      @user_events_organizing << Event.find(event_id) :
      @user_events << Event.find(event_id)
    end
  end

    private


  def own_profil?
    unless current_user == User.find_by(id: params[:id])
      flash[:danger] = "Stalking is creepy."
      redirect_to :root
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container-fuild">
  <div class="row">
    
  <%= render "admin/side_nav"%>


    <main class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Email</th>
              <th>Description</th>
              <th>Register date</th>
              <th>Admin</th>
            </tr>
          </thead>
          <tbody>

            <% @users.each do |user| %>
              <tr style="cursor: pointer;", onclick="location.href='<%= admin_user_path(user) %>'">
                <td><%= user.id %></td>
                <td><%= user.first_name + " "  + user.last_name %></td>
                <td><%= user.email %></td>
                <td><%= user.description[0..20].gsub(/\s\w+\s*$/, ' ...') %></td>
                <td><%= user.created_at %></td>
                <td><%= user.is_admin %></td>
              </tr>
            <% end %>
            
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container-fluid">
  <div class="row">

  <%= render "/admin/side_nav" %>
<br><br>

<div class="container">
  <div class="card text-center">
    <div class="card-header">
      <h2><%= @user.first_name + ' ' + @user.last_name%></h2>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @user.email %></h5>
      <p class="card-text"><em><%= @user.description %></em></p>
    </div>
    <div class="card-footer text-muted">
    <br>

    <div>
      <%= link_to '<button type="button" class="btn btn-info btn-block">Edit</button>'.html_safe, admin_index_path %>
    </div>
    <br>
    


      <div id="accordion">
        <div class="card">
          <div class="card-header" id="headingOne">
            <h5 class="mb-0">
              <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                Participate:
              </button>
            </h5>
          </div>
          <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
              <ul>
              <% @user_events.each do |event| %>
                <li><p><%= event.title %></p></li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>



        <div class="card">
          <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Organize:
              </button>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
              <ul>
              <% @user_events_organizing.each do |event_o| %>
                <li><p><%= event_o.title %></p></li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
</div>
</div>