config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, :events
  end
  get '/admin', to: 'admins#index', as: 'admin_index'


  root 'events#index'

  get 'events_controller/index'
  get 'static_pages/index'
  get 'static_pages/secret'
  
  resources :events do
    resources :attendances, only: [:index, :create]
  end
  resources :charges, only: [:new, :create]
  devise_for :users
  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end




# Envie de t'amuser ? 
#
# Tente avec ce fichier de routes, et tente de te connecter :
#
#
# root 'events#index'
#
# get 'static_pages/secret' 
# resources :events_controller, only: [:index]          #kécécé ?
# resources :static_pages, only: [:index, :secret]
# resources :events
# resources :users, only: [:show]
# devise_for :users

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/darkly/bootstrap.min.css" rel="stylesheet" integrity="sha384-w+8Gqjk9Cuo6XH9HKHG5t5I1VR4YBNdPt/29vwgfZR485eoEJZ8rJRbm3TR32P6k" crossorigin="anonymous">
    <title>EventbriteProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="/">EventBrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Nouvel event", new_event_path, class: "nav-link" %>
          </li>
        </ul>

        <form class="form-inline mt-2 mt-md-0">
         



           <% if user_signed_in?.! %>
            <div class="dropdown">
              <button class="btn btn-outline-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Login / Register
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Inscription", new_user_registration_path, class: "nav-link dropdown-item" %>
                <%= link_to 'Connexion', new_user_session_path, class: "nav-link dropdown-item" %>
              </div>
            </div>

          <% else %>

          <div class="dropdown">
              <button class="btn btn-outline-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profil / Logout
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'Profil', user_path(current_user.id), class: "nav-link dropdown-item" %>
                <%= link_to 'Deconnexion', destroy_user_session_path(current_user), method: "delete", class: "nav-link dropdown-item" %>
              
                <% if current_user.is_admin? %>

                  <%= link_to 'Administration', admin_index_path, class: "nav-link dropdown-item" %>

                <% end %>
              </div>
            </div>
    
          <% end %>
        </form>

      </div>
    </nav>


    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>


    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>